version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5002:5002" 

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001" 
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/app.py:/app/app.py

  redis:
    image: redis
    container_name: redis_container1
    ports: 
      - "6379:6379"
