version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5002:5002" # Map host port 8000 to container port 8000

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001" 